"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getColummMetadata = exports.getTableMetadata = exports.getDataSetMetadata = exports.mapTypeScriptTypeToBigQuery = exports.SchemaBuilder = void 0;
var SchemaBuilder_1 = require("./SchemaBuilder");
Object.defineProperty(exports, "SchemaBuilder", { enumerable: true, get: function () { return SchemaBuilder_1.SchemaBuilder; } });
var type_mapper_1 = require("./type-mapper");
Object.defineProperty(exports, "mapTypeScriptTypeToBigQuery", { enumerable: true, get: function () { return type_mapper_1.mapTypeScriptTypeToBigQuery; } });
var getMetadata_1 = require("./getMetadata");
Object.defineProperty(exports, "getDataSetMetadata", { enumerable: true, get: function () { return getMetadata_1.getDataSetMetadata; } });
Object.defineProperty(exports, "getTableMetadata", { enumerable: true, get: function () { return getMetadata_1.getTableMetadata; } });
Object.defineProperty(exports, "getColummMetadata", { enumerable: true, get: function () { return getMetadata_1.getColummMetadata; } });
